### ISSUE TITLE
Idea: How to include or excludue the files that we move to GCP

### ISSUE THREAD

**Issue by BKM01** [lahsivjar/gcp-storage-wagon#24]
Hey!! I would like to know if there is a way, I can send only the ".jars" to our Google Cloud Storage. Currently it is transferring all the files including the com , src folders and few unnecessary files. 

Basically, my development team requires only the .jar files that mvn build provides.

Please let me know your thoughts on the same. Thank you!

**Comment by lahsivjar** [comment]
Hi @BKM01 ,

From what I understand you don't want to deploy source files. You can configure source artifacts via maven: https://www.mkyong.com/maven/generate-source-code-jar-for-maven-based-project/

**Comment by lahsivjar** [comment]
Closing the issue, feel free to reopen for more discussions if required
