### ISSUE TITLE
Anonymous caller does not have storage.objects.get access

### ISSUE THREAD

**Issue by ashkaps** [lahsivjar/gcp-storage-wagon#28]
I am using this plugin to download artifacts from my maven repo hosted in buckets.
I am setting GOOGLE_APPLICATION_CREDENTIALS to a service account json which has admin access to this repo.
Is there some config I am missing?

Setup:
I have a library project that I have deployed using maven to google buckets using this plugin - worked.
In a second project I am using dependency of first project which is throwing below error when I am building using jenkins.
I have a jenkins slave setup on a client side server who is not in my GCP network thereby causing the need to specify service account to access maven repo.

This works fine inside my GCP network VMs because they are authenticated internally.
Thoughts?

Is there a way by which I can specify in my pom the path to service.json which is part of project 2?

I have check and GOOGLE_APPLICATION_CREDENTIALS is set correctly.
I have rechecked the permissions on that service account.

```
- members:
  - serviceAccount:maven@myproject.iam.gserviceaccount.com
  role: roles/storage.admin
```
 ```
{
[ERROR]   "code" : 401,
[ERROR]   "errors" : [ {
[ERROR]     "domain" : "global",
[ERROR]     "location" : "Authorization",
[ERROR]     "locationType" : "header",
[ERROR]     "message" : "Anonymous caller does not have storage.objects.get access to myrepo/snapshot/myproject/project/2.6.3/project-2.6.3.pom.",
[ERROR]     "reason" : "required"
[ERROR]   } ],
[ERROR]   "message" : "Anonymous caller does not have storage.objects.get access to mymavenreporsitory/....."
[ERROR] }
```

**Comment by ashkaps** [comment]
@lahsivjar any thoughts?

**Comment by YvesDautremay** [comment]
Same problem here

**Comment by ashkaps** [comment]
@YvesDautremay if you can explain your setup i can probably help.
I was able to resolve my issue.

**Comment by YvesDautremay** [comment]
Thanks for the help :)
I use a service account which has read/write access to the bucket I'm using. I managed to upload an artifact with the wagon on my lib project.
On the project where I want to use the lib, I declare the extension and the repositories in the pom. I use the same service account and have the following error :
 [ERROR] {
 [ERROR]   "code" : 401,
 [ERROR]   "errors" : [ {
 [ERROR]     "domain" : "global",
 [ERROR]     "location" : "Authorization",
 [ERROR]     "locationType" : "header",
 [ERROR]     "message" : "Anonymous caller does not have storage.objects.get access to bucket-bgv-dev-maven/snapshot/bgv/utils/authentication-utils/1.0.0/authentication-utils-1.0.0.pom.",
 [ERROR]     "reason" : "required"
 [ERROR]   } ],
 [ERROR]   "message" : "Anonymous caller does not have storage.objects.get access to bucket-bgv-dev-maven/snapshot/bgv/utils/authentication-utils/1.0.0/authentication-utils-1.0.0.pom."
 [ERROR] }

Yet I use the credentials as env variable during the build

**Comment by ashkaps** [comment]
How are you launching your other project where you want to use your artifact?
I mean are you using jenkins or other build mechanism or local? or something else?

**Comment by YvesDautremay** [comment]
I'm using Gitlab CI
Here's my build :
```
build:
  stage: build
  image: maven:3-jdk-11
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    GOOGLE_APPLICATION_CREDENTIALS: $GCP_SERVICE_CREDS
  script:
    - cat $GCP_SERVICE_CREDS
    - mvn -B install
  cache:
    paths:
      - .m2/repository/
```

The cat command outputs the credentials as expected and I still have the 401 error

**Comment by YvesDautremay** [comment]
Finally made it to work

I had to export the variable in the script
```
  script:
    - export GOOGLE_APPLICATION_CREDENTIALS=$GCP_SERVICE_CREDS
    - mvn -B package
```
Don't know why declaring it as a variable does not work

**Comment by lahsivjar** [comment]
Closing the issue since it seems resolved, please reopen if needed
